### PR TITLE
Sequence Diagrams

### PR DESCRIPTION
**Pull request by MithishR**
Added the sequence diagrams for both use cases and scrum meeting week 9

### CODE REVIEW

**Comment by mahigangal** [comment]
Both sequence diagrams are consistent with the class diagram and display different user cases.

**Review by mahigangal — COMMENTED** [review]
Both sequence diagrams are consistent with the class diagram and display different user cases.

**Comment by ojusharma** [comment]
The formatting and data in the sequence diagram is completely reflective of our discussion in the last scrum meeting.

**Review by mahigangal — APPROVED** [review]
Both sequence diagrams are consistent with the class diagram and display different user cases.

**Pull request merged**
